version: '3.8'

services:
  # Backend API em Python (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: roadtask_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://database:27017
      - DATABASE_NAME=roadtask_db
    volumes:
      - ./backend/data:/app/data
    depends_on:
      - database

  # Banco de Dados Não Relacional (MongoDB)
  database:
    image: mongo:6.0
    container_name: roadtask_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
